#!/bin/bash

# Read memory in kB
mem_total_kb=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
mem_available_kb=$(awk '/MemAvailable/ {print $2}' /proc/meminfo)

# Convert to GB (integer)
mem_used_gb=$(( (mem_total_kb - mem_available_kb + 1024*1024 - 1) / 1024 / 1024 ))
# Round up total memory
mem_total_gb=$(( (mem_total_kb + 1024*1024 - 1) / 1024 / 1024 ))

echo "${mem_used_gb}/${mem_total_gb}"
